[package]
name = "note_app"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27.0"
egui = "0.31.1"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rfd = "0.15.3"